name: pull_request

on:
  pull_request:
    branches:
      - main

jobs:
  terraform_plan:
    runs-on: ubuntu-20.04
    env:
      TF_IN_AUTOMATION: true
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Terraform Init
        run: docker build --build-arg AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} --build-arg AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} --tag opensource-infrastructure .

      - name: Terraform Import
        run: docker run --rm opensource-infrastructure import github-infrastructure -var="github_token=${GITHUB_TOKEN}"

      - name: Terraform Plan
        run: docker run --rm opensource-infrastructure plan -input=false -var="github_token=${GITHUB_TOKEN}"
