name: push_to_main

on:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    runs-on: ubuntu-20.04
    env:
      TF_IN_AUTOMATION: true
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3.4.0

      - name: Terraform Init
        run: docker build --build-arg AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} --build-arg AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} --tag opensource-infrastructure .

      - name: Terraform Apply
        run: docker run --rm opensource-infrastructure apply -input=false -auto-approve -var="github_token=${GITHUB_TOKEN}"
